name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        run: |
          curl -fsSL https://deno.land/install.sh | sh
          echo "DENO_INSTALL=$HOME/.deno" >> $GITHUB_ENV
          echo "$HOME/.deno/bin" >> $GITHUB_PATH

      - name: Cache Deno dependencies
        run: deno cache deps.ts

      - name: Build package
        run: deno task build

      - name: Prepare for publishing
        run: deno run -A build.ts

      - name: Publish package
        run: deno run -A publish.ts